### ISSUE TITLE
Use cssnano as peerDeps or allow update to version 4

### ISSUE THREAD

**Issue by evilebottnawi** [NMFR/optimize-css-assets-webpack-plugin#11]
https://github.com/ben-eb/cssnano/releases/tag/v4.0.0-rc.0

**Comment by NMFR** [comment]
Yeah you are right we should move cssnano to a peer dependency since its a default. 
Will change in the weekend.

**Comment by NMFR** [comment]
Done and published [v2.0.0](https://github.com/NMFR/optimize-css-assets-webpack-plugin/releases/tag/v2.0.0).
Major version bump because it's a breaking change.

**Comment by evilebottnawi** [comment]
@NMFR current semver not covers `alpha`, `beta` and etc. Just try ` "cssnano": "~4.0.0-rc.0",` and your get `UNMET PEER DEPENDENCY cssnano@4.0.0-rc.0`, best solution for this use peerDeps with `*`.

**Comment by NMFR** [comment]
Its not wise to include alpha and beta versions in dependencies.
With peer dependencies it allows you to control what version to use.
If you want to use a alpha version you can, just ignore the UNMET PEER DEPENDENCY from npm install, it should still work.

**Comment by albertogasparin** [comment]
Sorry @NMFR, but I'm a bit puzzled by this peer dependency update.
I personally think that 99% of the users of this package are happy to use cssnano.
If someone wants to use something different (even a different version like @evilebottnawi), they could already define it in the options (the downside is that they will have an unused version of cssnano installed, but I think it is a negligible side effect).

With version 2.0 you are making life harder for all consumers: if my project requires v4.x and your plugin requires v3.x there is a conflict that cannot be resolved unless I decide to downgrade my version or you to upgrade your peerDependency requirement.

On top of that:
- users that just want to use your plugin, now need to manually handle cssnano dependency (install, update, etc) otherwise this plugin is useless
- if consumers have a different version of cssnano other than the one defined in your peer dependency, they will get a warning at best (really annoying) or your plugin will stop working if versions are not compatible
- if consumers don't want to use cssnano, they will get a warning too!

Thats why I find defining cssnano as standard dependency was a better choice (enforcing convention over configuration) and I'd like to ask you to revisit your change.

**Comment by evilebottnawi** [comment]
@albertogasparin please read https://nodejs.org/en/blog/npm/peer-dependencies/, `cssnano` by definition is peer dependencies. The user has the right to choose the version he wants to use, without installing an extra package of the old version, I'm very worried about size of dependencies, since the number of packets affects the size of the collected docker container, which is very important. Also `cssnano` seems as plugin for `cssProcessor` function and should be used as `peerDeps`.

**Comment by albertogasparin** [comment]
I think it depends more on how @NMFR sees the future of this plugin. If it is going to be an utility to make any css compressor process the css file or if it will remain tidied to cssnano. 
On the former use case, I would compare this plugin to `postcss`. Postcss does not define `autoprefixer` as a peerDependency, it's up to you to install the version you want. Same here with `cssnano`, `cleancss` or any other compressor this plugin might support. optionalDeps looks like a better place where to define them.
On the latter use case, cssnano should be a dependency because the custom compressor is considered a secondary feature, and so the author should make the life easier to people he thinks are the core user base. The 3.x/4.x duplication is just momentary and after 4.0 release I don't see anyone using the old version, so manually installing it becomes just a complication. 

I don't mind any of the two landscapes, however I think the current "in-between" solution is not optimal.

**Comment by evilebottnawi** [comment]
@albertogasparin two version `cssnano` is bad. Old `cssnano` also install many deprecated packages and your `node_modules` become not small (https://github.com/ben-eb/cssnano/blob/v3.10.0/package.json#L25). Write a line with the desired version `cssnano` is more simple and best solution.

**Comment by NMFR** [comment]
@albertogasparin does have some valid points.

The reasoning behind the change (at least is my mind) was that cssnano was a default and if another CSS processor was supplied it would be completely unused (but installed). So the ``` peerDependencies ``` seemed like a natural solution. But i did not anticipate that it could create conflicts if a cssnano version was already installed for some other propose.

The original idea behind the ``` cssProcessor ``` option was to allow the user to do some extra manipulation of the CSS (prefix some comment like ````/* Author: ... */ ````, use some multiple libraries to manipulate the CSS, ...). But it is indeed a secondary feature.

I am inclined to revert this change because:
  - I also believe the majority of the use cases of this plugin do use the default.
  - The cssnano version conflict if already installed for other usage is real.
  - The memory footprint issue that @evilebottnawi raises is negligible because this is a plugin that should mainly be used for building apps and it would not end up included in any final app bundle (lets not forget that the dependency for this plugin should be in the ``` devDependencies ```). Of course this assumes a web app build scenario but other scenarios should be a minority.
  - The feature of using another version of cssnano is still there (because you can always install cssnano explicitly and pass your own version in the ``` cssProcessor ``` option). 
  - The ``` peerDependencies ``` is a bit annoying (but it is a "do once" kind of thing).

Any strong arguments against the revert of the ``` peerDependencies ``` change?

@evilebottnawi can you elaborate why the memory footprint issue seems so important in your case? Doesn't npm cache mitigate the issue? 

PS: Thanks @albertogasparin for the feedback.

**Comment by evilebottnawi** [comment]
@NMFR i have service to compare some `webpack` config online and `cssnano` can't be in `devDependencies` for me, also each plugin for old `cssnano` have deps as `postcss` v5 and other packages such as `postcss-selector-parser` and etc for `postcss` v5, it is create many extra unnecessary packages in `node_modules`. 

Also `optimize-css-assets-webpack-plugin` have description `A Webpack plugin to optimize \ minimize CSS assets.`. If your want to use `cssnano` as `deps` your should have `optimize-css-assets-using-cssnano-webpack-plugin` (or something similar) name. 

`cssProcessor` it is option to allow use any postcss based plugin for minification (by default it is `cssnano`). Using `cssnano` as deps is misleading for name, description and other docs.

Don't see problems to just add `cssnano` as deps in own package. All option which can be override (related to `cssProcessor`) and using external modules put in `peerDeps`.

**Comment by evilebottnawi** [comment]
You can take this into account or not, but working in `webpack` and `webpack-contrib` give many experience with same things. And `cssnano` should be put as `peerDeps`.

**Comment by evilebottnawi** [comment]
@NMFR Let's see on `imagemin`, 99% users use default preset such as `gifsicle`, `jpegtran`, `optipng` and `svgo`. But `imagemin` don't have their in deps, each user should be add this package manually.

**Comment by albertogasparin** [comment]
@evilebottnawi: if @NMFR will update the version of cssnano to v4.0 in a few weeks (or even sooner if v4.0-rc is stable) then your argument around using another version of cssnano will no longer apply, right?
If so, why not having @NMFR test cssnano v4 integration and publish a `optimize-css-assets-webpack-plugin@v3.0.0-beta` so people can already start using it (as I'm also looking forward cssnano@v4) . Then, once cssnano is no longer `-rc` @NMFR can publish his plugin v3.0.0 final and everybody will just get it.

**Comment by evilebottnawi** [comment]
@albertogasparin just read above, i can use other css minification based on `postcss`

**Comment by NMFR** [comment]
Ok with version `3.0.0` `cssnano` is back on the `dependencies` (for me it makes more sense because its the most used use case).

@evilebottnawi if you really need to not have the default `cssnano` installed you can use the [`last-call-webpack-plugin`](https://github.com/NMFR/last-call-webpack-plugin) (which this plugin also uses). Something like this:

``` javascript
var LastCallWebpackPlugin = require('last-call-webpack-plugin');
module.exports = {
  module: {
    loaders: [
      { test: /\.css$/, loader: ExtractTextPlugin.extract("style-loader", "css-loader") }
    ]
  },
  plugins: [
    new ExtractTextPlugin("styles.css"),
    new LastCallWebpackPlugin({
      assetProcessors: [
        {
          regExp: /\.css$/g,
          processor: function (assetName, asset) {
            return cssnano.process(asset.source()).then(r => r.css);
          },
        }
      ],
      canPrint: true
    })
  ]
}
```

Sorry for taking so long to solve this.

@evilebottnawi and @albertogasparin thanks for the help.
