### ISSUE TITLE
css source map have no chunk id, see img

### ISSUE THREAD

**Issue by ymqy** [NMFR/optimize-css-assets-webpack-plugin#22]
![image](https://user-images.githubusercontent.com/22427967/30632068-6538a642-9dac-11e7-8255-e909b898997e.png)
##  this is my config
```  
   new OptimizeCSSPlugin({
      assetNameRegExp: /.css$/g,
      cssProcessor: require('cssnano'),
      cssProcessorOptions: {
        safe: true,
        map: { inline: false },
      },
      canPrint: true,
    }),
```

**Comment by ymqy** [comment]
if i don't use OptimizeCSSPlugin, chunk id will show, but build time will slow 1s+,

**Comment by NMFR** [comment]
Do you really need the asset to have a chunk id?
May i ask why?

**Comment by ymqy** [comment]
sorry about the question, i don't know whether need

**Comment by NMFR** [comment]
I was asking because i don't know for what is used :p

I couldn't find information for what chunkId is used. I was under the impression that since the map assets was generated from the CSS it did not interact with chunks (its generated closer to the assets / files part of the pipeline). But from the print screen the map.js file does seem to have the same chunkIds of its source file (.js).

Can you give me some more information about this?

**Comment by ymqy** [comment]
Sorry，I can't give you more infomation, For webpack, I'm still exploring
