### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by mjprude** [NMFR/optimize-css-assets-webpack-plugin#31]
@NMFR thanks so much for your work on this project!

My organization recently starting using the plugin on one of our projects, but I saw the tests are still a work in progress. Are you open to a contributors to get the plugin tested? If so I'd be happy to help, and would welcome any thoughts you have on what those tests should look like.

**Comment by NMFR** [comment]
Thanks.
I am definitely open to a contributors. 
I had planned to setup some unit tests in the `tests` branch but didn't had time to do it yet.

My original plan was to test:
- The plugin interface:
  - Ensure only files that match the `assetNameRegExp` option get processed by the plugin.
  - Ensure that `cssProcessor` gets called with the passed `cssProcessorOptions` object and the value returned by the Promise (returned by calling `cssProcessor`) ends up written to the asset.
- Functionality:
  - Simple CSS optimization test, something like:
    index.js
    ``` javascript
    require('a.css');
    require('b.css');
    ```
    a.css
    ``` stylesheet
    body { color: red; }
    a { color: blue; }
    ```
    b.css
    ``` stylesheet
    body { color: red; }
    p { color: green;; }
    ```
    Verifying that the body rule is not duplicated.
  - Check if the plugin correctly works / plays well with:
    - webpack-subresource-integrity
    - compression-webpack-plugin

It was just a initial approach, open to suggestions / improvements.

**Comment by NMFR** [comment]
FYI: 

I switched to ES6 classes in the new `optimize-css-assets-webpack-plugin@4.0.0` version (to support the new webpack v4 plugin API) since node 4 is no longer supported by webpack v4.

This change seems to cause the following error:

```
TypeError: Class constructor LastCallWebpackPlugin cannot be invoked without 'new'
```

In the test branch https://github.com/cnerepo/optimize-css-assets-webpack-plugin/tree/feature/tests.

The reason seems to be that the `OptimizeCssAssetsWebpackPlugin` class extends the `LastCallWebpackPlugin` class from the `last-call-webpack-plugin` repo. Both classes are ES6 classes but jest seems to be transpiling `OptimizeCssAssetsWebpackPlugin` via babel but `LastCallWebpackPlugin` remains untouched by babel. This causes `OptimizeCssAssetsWebpackPlugin` to be a ES5 class that extends `LastCallWebpackPlugin` (a ES6 class). And this causes the error. 

I suggest either not using babel altogether or making babel transpile the `last-call-webpack-plugin` dependency.

Just linking https://github.com/cnerepo/optimize-css-assets-webpack-plugin/pull/1 and https://github.com/cnerepo/optimize-css-assets-webpack-plugin/pull/3 to be aware of this.
