### ISSUE TITLE
Can I see somewhere what cssProcessorOptions can I use?

### ISSUE THREAD

**Issue by gabrielkaputa** [NMFR/optimize-css-assets-webpack-plugin#37]
Hey,

this would really help. I tried to go to cssnano docs and figure out what options can I use but it seems like I couldn't figure it out. Is there any place I can learn what options can I use? Thanks

**Comment by NMFR** [comment]
Not sure if i can really help. `cssnano` uses a lot of `postcss` plugins ([see](http://cssnano.co/optimisations/)). I can't find documentation on its options. I suggest opening a ticket on [`cssnano` repo](https://github.com/ben-eb/cssnano/issues) for this.

Closing this issue since its a cssnano issue.
