### ISSUE TITLE
Althought it uses CSS Nano, it doesn't know how to read cssnano.config.js

### ISSUE THREAD

**Issue by bs-thomas** [NMFR/optimize-css-assets-webpack-plugin#49]
As per the topic, it doesn't read the config options from cssnano.config.js automatically it seems.  Anyone facing the same issue?

**Comment by bs-thomas** [comment]
Do you mean by setting this it will read from cssnano.config.js automatically?

(Im outside so I haven't tried.  But I'm eager to know)

**Comment by NMFR** [comment]
`optimize-css-assets-webpack-plugin` does not read `cssnano.config.js`. I don't know if `cssnano` only reads this file in CLI mode or if something is failing in `cssnano` side. Currently you can control the `cssnano` configuration with the `cssProcessorOptions` property.

Now the question is, if this is not a `cssnano` bug (`cssnano` only reads the file in CLI mode) should `optimize-css-assets-webpack-plugin` support reading the file to configure `cssnano`?

My first inclination is on "No", because `cssnano` is a default processor and you can pass any CSS processor. Also it might get tricky trying to identify if someone passes `cssnano` as a `cssProcessor` explicitly. 

Feedback on this is welcomed :)

**Comment by bs-thomas** [comment]
Well just FYI, in the days of Webpack 3, I used to include this step in my postcss loader (which I defined inside postcss.config.js).

So yes, the flow goes like this:

1. webpack.config.js reads postcss.config.js via loader
2. postcss.config.js reads cssnano.config.js via plugin definition

Currently with Webpack 4's change, I feel that the experience and code is downgraded, because I'm forced to define my cssnano config inside my webpack.config.js, and not via the recommended method of using cssnano.config.js

**Comment by NMFR** [comment]
It seems (did not test it) that `cssnano` always reads the config file in v4 (http://cssnano.co/guides/presets/). I'll wait for the release of a stable version of `cssnano` v4 until i revisit this issue.

**Comment by qkdreyer** [comment]
Any updates ?

**Comment by NMFR** [comment]
Can you try with `optimize-css-assets-webpack-plugin@5.0.0`? `cssnano` was updated to v4 in that version.

**Comment by mweibel** [comment]
I tried it `optimize-css-assets-webpack-plugin@5.0.0` and the config in package.json -> works well. 
I didn't try with a separate config file, but I assume that works too.
